### PR TITLE
build instead of repackaging pypi wheel

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Now that conda-forge has a working tensorflow we can actually build this package instead of just repackaging pypi!

### CODE REVIEW

**Comment by izahn** [comment]
All checks are passing, Ready for review

**Comment by jschueller** [comment]
can you rebase to master ?

**Comment by izahn** [comment]
> can you rebase to master ?

Done, thank you! 

Note that there are two issues here that I'm not 100% sure about. The first is that `tensorflow` is a build dependency, but if I add it there `conda` complains that `tensorflow-estimator` cannot depend on itself. Second, the PyPi package is `noarch` from what I can tell, despite the inclusion of compiled `c` code. I've replicated the `noarch` status here as well, but not so sure that is correct.

**Comment by jschueller** [comment]
I dont see c code being compiled anywhere, what are you referring to ?
The wheel file also doesnt have compiled libs either, so I'm not sure it requires tensorflow or any compiler at build.

**Comment by izahn** [comment]
> I dont see c code being compiled anywhere, what are you referring to ?

Well, there may not actually be. But `bazel` will complain that it can't find a  compiler if omit `{{ compiler('c') }}` from the build dependencies.

> The wheel file also doesnt have compiled libs either, so I'm not sure it requires tensorflow or any compiler at build.

If you don't install tensorflow in the build environment you will get
```
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Analyzing: target //tensorflow_estimator/tools/pip_package:build_pip_package (1 packages loaded, 0 targets configured)
Analyzing: target //tensorflow_estimator/tools/pip_package:build_pip_package (11 packages loaded, 27 targets configured)
Analyzing: target //tensorflow_estimator/tools/pip_package:build_pip_package (14 packages loaded, 162 targets configured)
Analyzing: target //tensorflow_estimator/tools/pip_package:build_pip_package (23 packages loaded, 196 targets configured)
INFO: Analyzed target //tensorflow_estimator/tools/pip_package:build_pip_package (26 packages loaded, 314 targets configured).
INFO: Found 1 target...
[0 / 4] [Prepa] BazelWorkspaceStatusAction stable-status.txt ... (2 actions, 0 running)
ERROR: /home/conda/feedstock_root/build_artifacts/tensorflow-estimator_1623680436837/work/tensorflow_estimator/python/estimator/api/BUILD:47:19: Executing genrule //tensorflow_estimator/python/estimator/api:estimator_python_api_gen_compat_v2 failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/tensorflow-estimator_1623680436837/_build_env/share/bazel/ac2ef406ba25ed8e48f7e3c7d6cbef99/sandbox/processwrapper-sandbox/1/execroot/org_tensorflow_estimator/bazel-out/k8-opt-exec-2B5CBBC6/bin/tensorflow_estimator/python/estimator/api/create_tensorflow_estimator.python.estimator_api_2_estimator_python_api_gen_compat_v2.runfiles/org_tensorflow_estimator/tensorflow_estimator/python/estimator/api/create_python_api_wrapper.py", line 26, in <module>
    from tensorflow_estimator.python.estimator import estimator_lib  # pylint: disable=unused-import
  File "/home/conda/feedstock_root/build_artifacts/tensorflow-estimator_1623680436837/_build_env/share/bazel/ac2ef406ba25ed8e48f7e3c7d6cbef99/sandbox/processwrapper-sandbox/1/execroot/org_tensorflow_estimator/bazel-out/k8-opt-exec-2B5CBBC6/bin/tensorflow_estimator/python/estimator/api/create_tensorflow_estimator.python.estimator_api_2_estimator_python_api_gen_compat_v2.runfiles/org_tensorflow_estimator/tensorflow_estimator/python/estimator/estimator_lib.py", line 22, in <module>
    from tensorflow_estimator.python.estimator.canned.baseline import BaselineClassifier
  File "/home/conda/feedstock_root/build_artifacts/tensorflow-estimator_1623680436837/_build_env/share/bazel/ac2ef406ba25ed8e48f7e3c7d6cbef99/sandbox/processwrapper-sandbox/1/execroot/org_tensorflow_estimator/bazel-out/k8-opt-exec-2B5CBBC6/bin/tensorflow_estimator/python/estimator/api/create_tensorflow_estimator.python.estimator_api_2_estimator_python_api_gen_compat_v2.runfiles/org_tensorflow_estimator/tensorflow_estimator/python/estimator/canned/baseline.py", line 53, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
```

**Pull request merged**
